name: Deploy API to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-140-252-95.us-east-2.compute.amazonaws.com << 'EOF'
          cd /home/ec2-user/expense_tracker
          git pull origin main
          docker build -t expense-tracker-api .
          docker run -d --env-file=.env-docker.sh -p 8001:8001 expense-tracker-api
        EOF
